# Generated by Django 3.1 on 2020-08-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eName', models.CharField(max_length=80)),
                ('eDesignation', models.CharField(max_length=50)),
                ('workLocation', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=20)),
                ('DOJ', models.CharField(max_length=20)),
                ('eContact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=30)),
                ('uPassword', models.CharField(max_length=30)),
            ],
        ),
    ]
